// <auto-generated />
using System;
using CadastroDeFuncionariosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroDeFuncionariosAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250402135249_Bug fixes")]
    partial class Bugfixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CadastroDeFuncionariosAPI.Models.Entities.Filho", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("DataDeNascimento")
                        .HasColumnType("date");

                    b.Property<string>("FuncionarioResponsavelCPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CPF");

                    b.HasIndex("FuncionarioResponsavelCPF");

                    b.ToTable("Filhos");
                });

            modelBuilder.Entity("CadastroDeFuncionariosAPI.Models.Entities.Funcionario", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("DataDeNascimento")
                        .HasColumnType("date");

                    b.Property<int>("Departamento")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salario")
                        .HasColumnType("float");

                    b.HasKey("CPF");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("CadastroDeFuncionariosAPI.Models.Entities.Filho", b =>
                {
                    b.HasOne("CadastroDeFuncionariosAPI.Models.Entities.Funcionario", "FuncionarioResponsavel")
                        .WithMany("Filhos")
                        .HasForeignKey("FuncionarioResponsavelCPF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuncionarioResponsavel");
                });

            modelBuilder.Entity("CadastroDeFuncionariosAPI.Models.Entities.Funcionario", b =>
                {
                    b.Navigation("Filhos");
                });
#pragma warning restore 612, 618
        }
    }
}
